server:
  port: 8989

spring:
  application:
    name: gateway
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
#    gateway:
#      routes:
#        - id: user_route
#          uri: http://localhost:9999/
#          predicates:
#            - Path=/feign/**
#        - id: product_route
#          uri: http://localhost:9998/
#          predicates:
#            - Path=/product/**
